---
nginx_proxy_manager_data_dir: /opt/nginx-proxy-manager
nginx_proxy_manager_http_port: 80
nginx_proxy_manager_https_port: 443
nginx_proxy_manager_ui_port: 81
nginx_proxy_manager_image: jc21/nginx-proxy-manager:latest
